/* FlowForge WebStudio - lightweight UI localization.
 * Deliberately translates only fixed editor chrome. It never scans the project
 * canvas or user-authored text, and uses no MutationObserver.
 */
(function(){
  'use strict';
  const LANGS=['pt-BR','en','es'];
  const STORAGE_KEY='flowforge.ui.language';
  const dict={
    'pt-BR':{
      'framework':'Framework','designer':'Designer','new':'Novo','save':'Salvar','open':'Abrir','examples':'Exemplos','export':'Exportar HTML','preview':'Preview',
      'tree':'Árvore','pages':'Páginas','assets':'Assets','free':'Livre','mobile':'📱 Mobile','tablet':'▯ Tablet','desktop':'▰ Desktop','page':'Página',
      'toolbox':'Toolbox','search':'Buscar componente...','toolhint':'Clique: adiciona • Arraste: posiciona • Duplo clique no componente: abre ação padrão',
      'design':'Design','code':'Código','blocks':'Blocos','debug':'Debug','properties':'Propriedades','actions':'Ações','name':'Nome','text':'Texto','background':'Background','color':'Cor',
      'visible':'Visible','enabled':'Enabled','frameworkStyle':'Usar estilo do framework','project':'Projeto','projectName':'Nome','type':'Tipo','frameworkCss':'Framework CSS','designerMode':'Modo do Designer',
      'viewport':'Viewport','widthHeight':'Largura × Altura','snap':'Snap 8px','duplicate':'Duplicar','delete':'Excluir','addAction':'＋ Adicionar ação',
      'actionsEvents':'Ações / Eventos','actionEmpty':'Selecione um componente para configurar suas ações.','addEvent':'Adicionar evento','visualAction':'Ação visual','quickActions':'Ações rápidas',
      'setProperty':'Alterar propriedade','show':'Mostrar','hide':'Ocultar','toggle':'Alternar','goPage':'Ir para página','navigate':'Navegar','openUrl':'Abrir URL','alert':'Mensagem','addClass':'Adicionar classe','play':'Play','pause':'Pause','storageSet':'LocalStorage','httpRequest':'HTTP GET',
      'target':'Alvo','property':'Propriedade','value':'Valor','addToEvent':'＋ Adicionar ao evento','clear':'Limpar','console':'Console','errors':'Erros','events':'Eventos','vars':'Variáveis','components':'Componentes','pause':'Pausar','resume':'Continuar','inspect':'Inspecionar','stopped':'Parado',
      'newProject':'Novo projeto','appHtml':'App HTML5','site':'Site','landing':'Landing Page','openProject':'Abrir projeto','tutorials':'Exemplos e tutoriais','close':'Fechar','cancel':'Cancelar','saveProject':'Salvar projeto','reviewSave':'Revise os dados do projeto antes de salvar.','projectVersion':'Versão','fileName':'Nome do arquivo','chooseIcon':'Escolher ícone','chooseFavicon':'Escolher favicon','remove':'Remover','noIcon':'Nenhum ícone selecionado','noFavicon':'Nenhum favicon selecionado','themeColor':'Cor do tema','saveFile':'Salvar arquivo','exportHtml':'Exportar HTML','exportOptional':'Escolha opcionalmente um ícone e um favicon para o HTML exportado.','useSavedIcon':'Usará o ícone salvo no projeto','useSavedFavicon':'Usará o favicon salvo no projeto','exportFile':'Exportar index.html','language':'Idioma',
      'customCss':'CSS próprio','flowforge':'FlowForge','appType':'App HTML5','siteType':'Site','landingType':'Landing Page',
      'frameworkHint':'O framework escolhido é incluído no HTML exportado via CDN.','designerHintFramework':'Framework: visualiza o estilo do projeto. FlowForge: visualiza o estilo nativo do editor.',
      'ok':'OK','undo':'Desfazer','redo':'Refazer','dockNone':'Dock: nenhum','top':'Top','bottom':'Bottom','left':'Left','right':'Right','fill':'Fill'
    },
    'en':{
      framework:'Framework',designer:'Designer',new:'New',save:'Save',open:'Open',examples:'Examples',export:'Export HTML',preview:'Preview',tree:'Outline',pages:'Pages',assets:'Assets',free:'Free',mobile:'📱 Mobile',tablet:'▯ Tablet',desktop:'▰ Desktop',page:'Page',toolbox:'Toolbox',search:'Search component...',toolhint:'Click: add • Drag: position • Double-click component: open default action',design:'Design',code:'Code',blocks:'Blocks',debug:'Debug',properties:'Properties',actions:'Actions',name:'Name',text:'Text',background:'Background',color:'Color',visible:'Visible',enabled:'Enabled',frameworkStyle:'Use framework style',project:'Project',projectName:'Name',type:'Type',frameworkCss:'CSS Framework',designerMode:'Designer mode',viewport:'Viewport',widthHeight:'Width × Height',snap:'Snap 8px',duplicate:'Duplicate',delete:'Delete',addAction:'＋ Add action',actionsEvents:'Actions / Events',actionEmpty:'Select a component to configure its actions.',addEvent:'Add event',visualAction:'Visual action',quickActions:'Quick actions',setProperty:'Change property',show:'Show',hide:'Hide',toggle:'Toggle',goPage:'Go to page',navigate:'Navigate',openUrl:'Open URL',alert:'Message',addClass:'Add class',play:'Play',pause:'Pause',storageSet:'LocalStorage',httpRequest:'HTTP GET',target:'Target',property:'Property',value:'Value',addToEvent:'＋ Add to event',clear:'Clear',console:'Console',errors:'Errors',events:'Events',vars:'Variables',components:'Components',resume:'Resume',inspect:'Inspect',stopped:'Stopped',newProject:'New project',appHtml:'HTML5 App',site:'Site',landing:'Landing Page',openProject:'Open project',tutorials:'Examples & tutorials',close:'Close',cancel:'Cancel',saveProject:'Save project',reviewSave:'Review the project data before saving.',projectVersion:'Version',fileName:'File name',chooseIcon:'Choose icon',chooseFavicon:'Choose favicon',remove:'Remove',noIcon:'No icon selected',noFavicon:'No favicon selected',themeColor:'Theme color',saveFile:'Save file',exportHtml:'Export HTML',exportOptional:'Optionally choose an icon and favicon for the exported HTML.',useSavedIcon:'Will use the icon saved in the project',useSavedFavicon:'Will use the favicon saved in the project',exportFile:'Export index.html',language:'Language',customCss:'Custom CSS',flowforge:'FlowForge',appType:'HTML5 App',siteType:'Site',landingType:'Landing Page',frameworkHint:'The selected framework is included in exported HTML via CDN.',designerHintFramework:'Framework: previews the project style. FlowForge: previews the editor native style.',ok:'OK',undo:'Undo',redo:'Redo',dockNone:'Dock: none',top:'Top',bottom:'Bottom',left:'Left',right:'Right',fill:'Fill'
    },
    'es':{
      framework:'Framework',designer:'Diseñador',new:'Nuevo',save:'Guardar',open:'Abrir',examples:'Ejemplos',export:'Exportar HTML',preview:'Vista previa',tree:'Árbol',pages:'Páginas',assets:'Assets',free:'Libre',mobile:'📱 Móvil',tablet:'▯ Tableta',desktop:'▰ Escritorio',page:'Página',toolbox:'Herramientas',search:'Buscar componente...',toolhint:'Clic: añade • Arrastra: posiciona • Doble clic en el componente: abre la acción predeterminada',design:'Diseño',code:'Código',blocks:'Bloques',debug:'Depurar',properties:'Propiedades',actions:'Acciones',name:'Nombre',text:'Texto',background:'Fondo',color:'Color',visible:'Visible',enabled:'Habilitado',frameworkStyle:'Usar estilo del framework',project:'Proyecto',projectName:'Nombre',type:'Tipo',frameworkCss:'Framework CSS',designerMode:'Modo del diseñador',viewport:'Viewport',widthHeight:'Ancho × Alto',snap:'Ajuste 8px',duplicate:'Duplicar',delete:'Eliminar',addAction:'＋ Añadir acción',actionsEvents:'Acciones / Eventos',actionEmpty:'Selecciona un componente para configurar sus acciones.',addEvent:'Añadir evento',visualAction:'Acción visual',quickActions:'Acciones rápidas',setProperty:'Cambiar propiedad',show:'Mostrar',hide:'Ocultar',toggle:'Alternar',goPage:'Ir a página',navigate:'Navegar',openUrl:'Abrir URL',alert:'Mensaje',addClass:'Añadir clase',play:'Reproducir',pause:'Pausar',storageSet:'LocalStorage',httpRequest:'HTTP GET',target:'Objetivo',property:'Propiedad',value:'Valor',addToEvent:'＋ Añadir al evento',clear:'Limpiar',console:'Consola',errors:'Errores',events:'Eventos',vars:'Variables',components:'Componentes',resume:'Continuar',inspect:'Inspeccionar',stopped:'Detenido',newProject:'Nuevo proyecto',appHtml:'App HTML5',site:'Sitio',landing:'Landing Page',openProject:'Abrir proyecto',tutorials:'Ejemplos y tutoriales',close:'Cerrar',cancel:'Cancelar',saveProject:'Guardar proyecto',reviewSave:'Revisa los datos del proyecto antes de guardar.',projectVersion:'Versión',fileName:'Nombre del archivo',chooseIcon:'Elegir icono',chooseFavicon:'Elegir favicon',remove:'Quitar',noIcon:'Ningún icono seleccionado',noFavicon:'Ningún favicon seleccionado',themeColor:'Color del tema',saveFile:'Guardar archivo',exportHtml:'Exportar HTML',exportOptional:'Elige opcionalmente un icono y un favicon para el HTML exportado.',useSavedIcon:'Usará el icono guardado en el proyecto',useSavedFavicon:'Usará el favicon guardado en el proyecto',exportFile:'Exportar index.html',language:'Idioma',customCss:'CSS propio',flowforge:'FlowForge',appType:'App HTML5',siteType:'Sitio',landingType:'Landing Page',frameworkHint:'El framework elegido se incluye en el HTML exportado mediante CDN.',designerHintFramework:'Framework: muestra el estilo del proyecto. FlowForge: muestra el estilo nativo del editor.',ok:'OK',undo:'Deshacer',redo:'Rehacer',dockNone:'Dock: ninguno',top:'Arriba',bottom:'Abajo',left:'Izquierda',right:'Derecha',fill:'Rellenar'
    }
  };
  const firstText=n=>{if(!n)return null;for(const c of n.childNodes)if(c.nodeType===Node.TEXT_NODE&&c.nodeValue.trim())return c;return null};
  const setNode=(sel,key)=>{const el=document.querySelector(sel),t=firstText(el);if(el&&t&&dict[current][key]!=null)t.nodeValue=t.nodeValue.replace(t.nodeValue.trim(),dict[current][key]);};
  const setText=(sel,key)=>{const el=document.querySelector(sel);if(el&&dict[current][key]!=null)el.textContent=dict[current][key]};
  const setAttr=(sel,attr,key)=>{const el=document.querySelector(sel);if(el&&dict[current][key]!=null)el.setAttribute(attr,dict[current][key])};
  const setOpt=(sel,values)=>{const el=document.querySelector(sel);if(!el)return;for(const [value,key] of Object.entries(values)){const o=el.querySelector(`option[value="${CSS.escape(value)}"]`);if(o&&dict[current][key]!=null)o.textContent=dict[current][key]}};
  let current='pt-BR';
  function normalize(v){v=(v||'').toLowerCase();if(v.startsWith('pt'))return'pt-BR';if(v.startsWith('es'))return'es';return'en'}
  function apply(){
    document.documentElement.lang=current;
    const d=dict[current];
    // Header and top toolbar
    setNode('.topFramework:not(#ffLanguageWrap)','framework');setNode('#ffLanguageWrap','language');
    [['#newBtn','new'],['#saveBtn','save'],['#openBtn','open'],['#examplesBtn','examples'],['#exportBtn','export'],['#previewBtn','preview'],['#outlineBtn','tree'],['#pagesBtn','pages'],['#assetsBtn','assets'],['#toolbox h3','toolbox'],['#tabs [data-tab="design"]','design'],['#tabs [data-tab="code"]','code'],['#tabs [data-tab="blocks"]','blocks'],['#debugBtn','debug'],['#propTab','properties'],['#actionTab','actions'],['#propertiesPanel>h3','properties'],['#propertiesPanel .propBtns #duplicateBtn','duplicate'],['#propertiesPanel .propBtns #deleteBtn','delete'],['#actionsPanel>h3','actionsEvents'],['#actionEmpty','actionEmpty'],['#actionsPanel .wide','addAction'],['#actionsPanel hr + h3','visualAction'],['#actionsPanel hr + h3 + div + small','quickActions'],['#saveProjectDlg h2','saveProject'],['#saveProjectDlg .exampleIntro','reviewSave'],['#confirmSaveProject','saveFile'],['#exportHtmlDlg h2','exportHtml'],['#exportHtmlDlg .exampleIntro','exportOptional'],['#confirmExportHtml','exportFile'],['#newDlg h2','newProject'],['#examplesDlg h2','tutorials']].forEach(([s,k])=>setNode(s,k));
    setAttr('#toolSearch','placeholder','search');
    setNode('#toolbox .toolHint','toolhint');
    setNode('#propertiesPanel .titleAuto','frameworkStyle');
    setNode('#propertiesPanel .ffVpSize','widthHeight');
    setNode('#saveProjectDlg label:nth-of-type(1)','projectName');
    setNode('#saveProjectDlg label:nth-of-type(2)','projectVersion');
    setNode('#saveProjectDlg label:nth-of-type(3)','fileName');
    setNode('#saveProjectDlg .assetField:nth-of-type(1)>label','chooseIcon');
    setNode('#saveProjectDlg .assetField:nth-of-type(2)>label','chooseFavicon');
    setNode('#saveProjectDlg #saveProjectIconPick','chooseIcon');setNode('#saveProjectDlg #saveProjectIconClear','remove');setNode('#saveProjectDlg #saveProjectFaviconPick','chooseFavicon');setNode('#saveProjectDlg #saveProjectFaviconClear','remove');
    setNode('#exportHtmlDlg #exportProjectIconPick','chooseIcon');setNode('#exportHtmlDlg #exportProjectIconClear','remove');setNode('#exportHtmlDlg #exportProjectFaviconPick','chooseFavicon');setNode('#exportHtmlDlg #exportProjectFaviconClear','remove');
    setNode('#saveProjectIconInfo','noIcon');setNode('#saveProjectFaviconInfo','noFavicon');setNode('#exportProjectIconInfo','useSavedIcon');setNode('#exportProjectFaviconInfo','useSavedFavicon');
    setOpt('#framework',{none:'customCss'});setOpt('#frameworkTop',{none:'customCss'});setOpt('#designerMode',{framework:'framework',flowforge:'flowforge'});setOpt('#designerModeTop',{framework:'framework',flowforge:'flowforge'});setOpt('#projectType',{app:'appType',site:'siteType',landing:'landingType'});setOpt('#viewport',{390:'mobile',768:'tablet',1200:'desktop'});setOpt('#devicePreset',{'':'free','390':'mobile','768':'tablet','1440':'desktop'});setOpt('#dockSelect',{'':'dockNone',top:'top',bottom:'bottom',left:'left',right:'right',fill:'fill'});
    document.title='FlowForge WebStudio';
    if(window.__ffI18nSelect)window.__ffI18nSelect.value=current;
  }
  function addSelector(){
    const header=document.querySelector('header');if(!header||document.getElementById('ffLanguage'))return;
    const label=document.createElement('label');label.className='topFramework';label.id='ffLanguageWrap';
    label.append('Idioma ');const sel=document.createElement('select');sel.id='ffLanguage';sel.innerHTML='<option value="pt-BR">Português</option><option value="en">English</option><option value="es">Español</option>';label.append(sel);header.insertBefore(label,header.querySelector('nav'));
    window.__ffI18nSelect=sel;sel.addEventListener('change',()=>{current=sel.value;localStorage.setItem(STORAGE_KEY,current);apply()});
  }
  function init(){
    const saved=localStorage.getItem(STORAGE_KEY);current=LANGS.includes(saved)?saved:normalize(navigator.language);addSelector();apply();
  }
  window.FlowForgeI18n={apply,setLanguage(lang){if(LANGS.includes(lang)){current=lang;localStorage.setItem(STORAGE_KEY,lang);apply()}},getLanguage:()=>current};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
