// Framework adapters v0.9.0
window.FlowForgeFrameworks={
 none:{name:'CSS próprio',button:'',input:'',select:'',textarea:'',file:'',badge:'',alert:'',card:''},
 bootstrap:{name:'Bootstrap 5.3',button:'btn btn-primary',input:'form-control',select:'form-select',textarea:'form-control',file:'form-control',badge:'badge text-bg-primary',alert:'alert alert-primary',card:'card'},
 bulma:{name:'Bulma',button:'button is-primary',input:'input',select:'select',textarea:'textarea',file:'file-input',badge:'tag is-primary',alert:'notification is-primary',card:'card'},
 pico:{name:'Pico CSS',button:'',input:'',select:'',textarea:'',file:'',badge:'',alert:'',card:''},
 tailwind:{name:'Tailwind CSS',button:'px-4 py-2 rounded bg-blue-600 text-white font-medium',input:'border rounded px-3 py-2 w-full',select:'border rounded px-3 py-2 w-full',textarea:'border rounded px-3 py-2 w-full',file:'border rounded px-3 py-2 w-full',badge:'inline-flex rounded-full px-2 py-1 text-xs font-semibold bg-blue-100 text-blue-800',alert:'rounded border p-4 bg-blue-50 text-blue-800',card:'rounded-lg border p-4 shadow-sm'},
 materialize:{name:'Materialize CSS',button:'btn waves-effect waves-light',input:'',select:'',textarea:'materialize-textarea',file:'',badge:'new badge',alert:'card-panel blue lighten-4 blue-text',card:'card'},
 foundation:{name:'Foundation',button:'button',input:'',select:'',textarea:'',file:'',badge:'badge',alert:'callout primary',card:'card'},
 uikit:{name:'UIkit',button:'uk-button uk-button-primary',input:'uk-input',select:'uk-select',textarea:'uk-textarea',file:'uk-input',badge:'uk-label uk-label-primary',alert:'uk-alert-primary',card:'uk-card uk-card-default uk-card-body'},
 semantic:{name:'Semantic UI',button:'ui primary button',input:'ui input',select:'ui dropdown',textarea:'ui input',file:'ui input',badge:'ui blue label',alert:'ui blue message',card:'ui card'}
};
FlowForge.registerModule('frameworks',{get:id=>FlowForgeFrameworks[id]||FlowForgeFrameworks.none,all:()=>Object.entries(FlowForgeFrameworks)});


// Scoped designer styles: these mirror the selected framework inside #stage only,
// so the IDE chrome itself is never affected by framework CSS.
window.FlowForgeFrameworkDesignerCSS={
  none:'',
  bootstrap:`#stage[data-framework="bootstrap"] .component button.btn{display:inline-block;font-weight:400;line-height:1.5;color:#fff;text-align:center;vertical-align:middle;cursor:pointer;background:#0d6efd;border:1px solid #0d6efd;border-radius:.375rem;padding:.375rem .75rem;font-size:1rem}#stage[data-framework="bootstrap"] .component input.form-control,#stage[data-framework="bootstrap"] .component textarea.form-control,#stage[data-framework="bootstrap"] .component select.form-select{display:block;width:100%;padding:.375rem .75rem;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;background:#fff;border:1px solid #dee2e6;border-radius:.375rem;box-sizing:border-box}#stage[data-framework="bootstrap"] .component .badge{display:inline-block;padding:.35em .65em;font-size:.75em;font-weight:700;line-height:1;color:#fff;background:#0d6efd;border-radius:.375rem}#stage[data-framework="bootstrap"] .component .alert{padding:1rem;margin:0;border:1px solid #9ec5fe;border-radius:.375rem;background:#cfe2ff;color:#084298}#stage[data-framework="bootstrap"] .component .card{border:1px solid rgba(0,0,0,.175);border-radius:.375rem;background:#fff;box-shadow:0 .125rem .25rem rgba(0,0,0,.075)}` ,
  bulma:`#stage[data-framework="bulma"] .component .button{align-items:center;border:1px solid transparent;border-radius:4px;box-shadow:none;display:inline-flex;font-size:1rem;height:2.5em;justify-content:center;padding:calc(.5em - 1px) 1em;background:#485fc7;color:#fff;font-weight:500}#stage[data-framework="bulma"] .component input.input,#stage[data-framework="bulma"] .component textarea.textarea{background:#fff;border:1px solid #dbdbdb;border-radius:4px;box-shadow:inset 0 .0625em .125em rgba(10,10,10,.05);box-sizing:border-box;padding:.5em .75em;width:100%;font-size:1rem}#stage[data-framework="bulma"] .component .tag{align-items:center;background:#eff1fa;border-radius:4px;color:#363636;display:inline-flex;font-size:.75rem;height:2em;padding:0 .75em}#stage[data-framework="bulma"] .component .notification{background:#f5f5f5;border-radius:4px;padding:1.25rem 2.5rem 1.25rem 1.5rem}` ,
  pico:`#stage[data-framework="pico"] .component button{border:1px solid #0172ad;border-radius:.5rem;background:#0172ad;color:#fff;padding:.6rem 1rem;font-weight:600}#stage[data-framework="pico"] .component input,#stage[data-framework="pico"] .component select,#stage[data-framework="pico"] .component textarea{width:100%;box-sizing:border-box;border:1px solid #cfd5db;border-radius:.5rem;padding:.65rem .75rem;background:#fff;color:#24303c}#stage[data-framework="pico"] .component .ff-badge{display:inline-block;border-radius:999px;padding:.25rem .65rem;background:#0172ad;color:#fff;font-size:.8rem}#stage[data-framework="pico"] .component .ff-card{border:1px solid #dfe3e8;border-radius:.75rem;padding:1rem;background:#fff}` ,
  tailwind:`#stage[data-framework="tailwind"] .component .px-4{padding-left:1rem;padding-right:1rem}#stage[data-framework="tailwind"] .component .py-2{padding-top:.5rem;padding-bottom:.5rem}#stage[data-framework="tailwind"] .component .rounded{border-radius:.25rem}#stage[data-framework="tailwind"] .component .bg-blue-600{background:#2563eb}#stage[data-framework="tailwind"] .component .text-white{color:#fff}#stage[data-framework="tailwind"] .component .font-medium{font-weight:500}#stage[data-framework="tailwind"] .component .border{border:1px solid #d1d5db}#stage[data-framework="tailwind"] .component .w-full{width:100%;box-sizing:border-box}#stage[data-framework="tailwind"] .component input,#stage[data-framework="tailwind"] .component select,#stage[data-framework="tailwind"] .component textarea{font:inherit}#stage[data-framework="tailwind"] .component .shadow-sm{box-shadow:0 1px 2px rgba(0,0,0,.05)}#stage[data-framework="tailwind"] .component .rounded-lg{border-radius:.5rem}` ,
  materialize:`#stage[data-framework="materialize"] .component .btn{background:#26a69a;border:0;border-radius:2px;color:#fff;display:inline-block;height:36px;line-height:36px;padding:0 16px;text-transform:uppercase;font-size:14px;box-shadow:0 2px 2px rgba(0,0,0,.14)}#stage[data-framework="materialize"] .component input,#stage[data-framework="materialize"] .component textarea{box-sizing:border-box;width:100%;border:0;border-bottom:1px solid #9e9e9e;padding:8px 0;background:transparent;outline:none}#stage[data-framework="materialize"] .component .new.badge{background:#26a69a;color:#fff;border-radius:2px;padding:2px 8px;font-size:12px}#stage[data-framework="materialize"] .component .card{background:#fff;border-radius:2px;box-shadow:0 2px 2px rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.12);padding:1rem}` ,
  foundation:`#stage[data-framework="foundation"] .component .button{display:inline-block;padding:.85em 1em;border:0;border-radius:0;background:#1779ba;color:#fff;font-size:.9rem;line-height:1;text-align:center}#stage[data-framework="foundation"] .component input,#stage[data-framework="foundation"] .component select,#stage[data-framework="foundation"] .component textarea{width:100%;box-sizing:border-box;border:1px solid #cacaca;border-radius:0;padding:.5rem;background:#fff;color:#0a0a0a}#stage[data-framework="foundation"] .component .badge{display:inline-block;min-width:2.1em;padding:.3em;background:#1779ba;color:#fff;border-radius:0;text-align:center}#stage[data-framework="foundation"] .component .callout{padding:1rem;border:1px solid rgba(10,10,10,.25);background:#f3f3f3}` ,
  uikit:`#stage[data-framework="uikit"] .component .uk-button{display:inline-block;box-sizing:border-box;padding:0 30px;vertical-align:middle;font-size:14px;line-height:38px;text-align:center;text-decoration:none;border:1px solid transparent;border-radius:0;background:#1e87f0;color:#fff}#stage[data-framework="uikit"] .component .uk-input,#stage[data-framework="uikit"] .component .uk-select,#stage[data-framework="uikit"] .component .uk-textarea{height:40px;max-width:100%;width:100%;border:1px solid #e5e5e5;padding:0 10px;background:#fff;box-sizing:border-box}#stage[data-framework="uikit"] .component .uk-label{display:inline-block;padding:0 10px;background:#1e87f0;color:#fff;font-size:12px;line-height:24px}#stage[data-framework="uikit"] .component .uk-alert-primary{padding:15px;background:#d8eafc;color:#1e87f0}#stage[data-framework="uikit"] .component .uk-card{padding:20px;background:#fff;box-shadow:0 5px 15px rgba(0,0,0,.08)}` ,
  semantic:`#stage[data-framework="semantic"] .component .ui.button{display:inline-block;min-height:1em;border:0;border-radius:.28571429rem;padding:.78571429em 1.5em;background:#e0e1e2;color:rgba(0,0,0,.6);font-weight:700}#stage[data-framework="semantic"] .component .ui.primary.button{background:#2185d0;color:#fff}#stage[data-framework="semantic"] .component .ui.input{display:inline-flex;align-items:center;width:100%;box-sizing:border-box}#stage[data-framework="semantic"] .component .ui.input input,#stage[data-framework="semantic"] .component textarea.ui.input{width:100%;padding:.67857143em 1em;border:1px solid rgba(34,36,38,.15);border-radius:.28571429rem;box-sizing:border-box}#stage[data-framework="semantic"] .component .ui.label{display:inline-block;padding:.5833em .833em;background:#e8e8e8;color:rgba(0,0,0,.6);border-radius:.28571429rem}#stage[data-framework="semantic"] .component .ui.blue.label{background:#2185d0;color:#fff}#stage[data-framework="semantic"] .component .ui.message{padding:1em 1.5em;background:#f8ffff;color:#276f86;border-radius:.28571429rem}#stage[data-framework="semantic"] .component .ui.card{background:#fff;border-radius:.28571429rem;box-shadow:0 1px 3px 0 rgba(34,36,38,.15);padding:1em}`
};
FlowForge.registerModule('framework-designer-css',{get:id=>FlowForgeFrameworkDesignerCSS[id]||'',all:()=>Object.entries(FlowForgeFrameworkDesignerCSS)});
